### ISSUE TITLE
Can not turn on the addon

### ISSUE THREAD

**Issue by thironaka0716** [sony/SR-Display-Plugin-Preview-BL#3]
I tried to add the addon on Blender 3.6.5.
But when I turn on the addon the error is occurred below.
How do I fix this error?

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\(user)\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\SpatialRealityDisplayPluginBle_1_0_0\__init__.py", line 35, in <module>
    import utils.CheckModal as CheckModal
ModuleNotFoundError: No module named 'utils.CheckModal'; 'utils' is not a package

**Comment by TE-YuichiMurakami** [comment]
@thironaka0716 
Thank you for your feedback. Please try either method.

"method 1"
Please checkout the branch "bugfix/resolve_path_import_bug" in this github and tyr once more.

"Method 2"
Please fix the following source code. (you can directly change the source code of official release.
https://www.sony.net/Products/Developer-Spatial-Reality-display/jp/dcc-tools/blender-plugin/

①
Replace the line 35 in SpatialRealityDisplayPluginBle_1_0_0__init__.py, which says `import utils.CheckModal as CheckModal`, with `from .utils import CheckModal`.
②
Comment out the line 15 in SpatialRealityDisplayPluginBle_1_0_0\SRDViewer\srdViewer.py, which says `import utils.CheckModal as CheckModal`.

**Comment by YuichiMurakami916** [comment]
@thironaka0716 
Thank you for your feedback. Please try either method.

"method 1"
Please checkout the branch "bugfix/resolve_path_import_bug" in this github and tyr once more.

"Method 2"
Please fix the following source code. (you can directly change the source code of official release.
https://www.sony.net/Products/Developer-Spatial-Reality-display/jp/dcc-tools/blender-plugin/

①
Replace the line 35 in SpatialRealityDisplayPluginBle_1_0_0__init__.py, which says import utils.CheckModal as CheckModal, with from .utils import CheckModal.
②
Comment out the line 15 in SpatialRealityDisplayPluginBle_1_0_0\SRDViewer\srdViewer.py, which says import utils.CheckModal as CheckModal.
